default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: good_night

development:
  <<: *default
  database: good_night_development

test:
  <<: *default
  database: good_night_test

production:
  <<: *default
  database: good_night_production
  username: good_night
  password: <%= ENV["GOOD_NIGHT_DATABASE_PASSWORD"] %>
